const kList1 =
    "ALERT:VIGILANT;ENTHUSIASTIC:ARDOR,AVID,DYNAMIC,EFFERVESCENT,EFFUSIVE,FERVENT,FRISKY,GUSHING,VIVACIOUS,ZEALOUS,ZEST;UNUSUAL:ABERRATION,ANOMALY;PERIODICALLY:FITFULLY,INTERMITTENT,OCCASIONAL~WITHOUT MISTAKE/PERFECT:FLAWLESS,IMMACULATE,IMPECCABLE,INTEGRITY,IRREPROACHABLE,UNIMPEACHABLE;NOT SERIOUS:BLITHE,FLIPPANT,FRIVOLOUS,INSOUCIANT;COUNTER-ATTACK:REPRISAL,RETALIATE;ATTRACTIVE:ARRESTING,DELECTABLE,ENTHRALL,INFATUATE,MESMERIZE,RAPTURE~ARGUE/FIGHT:ALTERCATION,BICKER,BRAWL,CONTEND,SQUABBLE,TUSSLE;NARROW MINDED:INSULAR,MYOPIC;READY INSIGHT:PERSPICUOUS;CONFUSING SITUATION:DILEMMA,PLIGHT,PREDICAMENT~INATTENTIVE:DISARM;DIFFICULT:ARDUOUS,CUMBERSOME,EXACTING,LABORIOUS,PONDEROUS;HARD WORKING :ASSIDUOUS,DILIGENT,INDUSTRIOUS,PAINSTAKING;SHORT LIVED:EPHEMERAL,EVANESCENT,TRANSIENT";

const kList2 =
    "IMMORAL:DEBAUCHERY,DECADENT,DEGENERATE,DEPRAVIFY,CIMPROBITY;IMPARTIAL:EGALITARIAN,EQUITABLE,EVENHANDED;NOT EQUAL:DISPARATE;STRANGE:ECCENTRIC,FOIBLE,QUIRKINESS~EXPERIENCED:SEASONED,VETERAN;FLUENT:ARTICULATE,COHERENT,ENUNCIATE;SUPPRESS:QUASH,SUBDUE;RESTRAIN:BRIDLE,CIRCUMSCRIBE,CONSTRAINT,MANACLE,SECURE,SHACKLE~INEXPERIENCED:APPRENTICE,NOVEL,NOVICE,ROOKIE;RESTORED:REGENERATE,REJUVENATE,RESUSCITATION,REVIVE;EQUALITY:COMMENSURATE,PEERS;LOYAL:FEALTY,FIDELITY~FEELING GUILTY:PENITENT,RUEFUL;TOO SERIOUS:GRAVE,GRAVITY;WIDESPREAD:EPIDEMIC,PANDEMIC,RIFE;DOUBTFUL:APOCRYPHAL,DUBIOUS,ERRONEOUS,FALLACIOUS,ILLICIT,PHONY,SHAM,SPECIOUS";

const kList3 =
    "INTROVERT:COY,DIFFIDENCE,RESERVED,TIMID,TIMOROUS;NOT EXPERT:LAYPERSON;PRAISE:ADULATION;FALSEHOOD:MENDACITY,PERJURY~SET FREE:EXTRICATE;DOMINATING:AUTHORITATIVE,DOCTRINAIRE,DOGMATIC,HEGEMONY,TOTALITARIAN,TYRANT;NOT ENTHUSIASTIC:DAMPEN,TEPID;INDIFFERENT:APATHY,STOIC~FAKE:COUNTERFEIT,FACTITIOUS;BIASED:BIGOT,DISCRIMINATORY,PREJUDICED;GAP:ABEYANCE,RESPITE;ACCUSE/DEFAME:ASPERSION,CALUMNY,MALIGN,OBLOQUY,SLANDER,SLUR,STIGMATIZATION~RUDE:BOOR,BRUSQUE,TERSE;PUZZLING:CONUNDRUM,CRYPTIC,GARBLE,LABYRINTH,MAZE;STRANGE:ABSURD,ATYPICAL,LUDICROUS,OUTLANDISH,PREPOSTEROUS;HARMONY:ACCORD,CONCORD,CONGRUOUS,CONSONANCE";

const kList4 =
    "FOREIGNER:EXOTIC;TO MAKE BETTER:ALLAY,ALLEVIATE,ASSUAGE,CONCILIATE,MITIGATE,MOLLIFY,PACIFY,PLACATE;NON-ATTRACTING:ENNUI;TO MAKE SEVER:EXACERBATE~HAPPY:ELATED,EUPHORIA,EXHILARATION,FELICITY,JEST,JOCULAR,JOLLITY,JOVIAL,JUBILANT,REGALE;NEVER ENDING:CHRONIC,INEXORABLE,INTERMINABLE,PERENNIAL,RELENTLESS;DISTURBED:AGITATED,CONSTERNATION,DISMAY,DISTRAUGHT,FAZE,FRENETIC,HYSTERICAL,OVERWROUGHT,PERTURB;NON WIDESPREAD:ENDEMIC~END:CEASE,TERMINATE;ORDINARY:BANAL,CLICHE,COMMONPLACE,HUMDRUM,MUNDANE,PLEBEIAN,QUOTIDIAN;IMMATURE:CALLOW,PUERILE;GENUINE:AUTHENTIC,LEGITIMATE~RIGHT TO VOTE:ENFRANCHISE,SUFFRAGE;CONTRADICT:IRONY,IRONIC,PARADOX;HARMFUL:ANATHEMA,BALEFUI,BANE,DELETERIOUS,DETRIMENTAL,MALIGNANT,PERNICIOUS;CRUCIAL/SIGNIFICANT:CORE,FOREMOST,INDISPENSIBLE,MANDATORY,PARAMOUNT,PIVOTAL";

const kList5 =
    "UNCLEAR:AMORPHOUS,BECLOUD,MURKY,NEBULOUS;LAZY:INDOLENT,LACKADAISICAL,LANGUID,LASSITUDE,LETHARGIC,SLOTH,SLUGGISH;TRUTH:VERACITY;AGGRESSIVE:BELLICOSE,BELLIGERENt,DISPUTATIOUS,FRACTIOUS,LITIGIOUS,POLEMICAl,TRUCULENT~DEVELOPING:EMBRYONIC,FLEDGLING,INCHOATE,INCIPIENT,NASCENT,RUDIMENTARY;BRAVE:AUDACIOUS,CHIVALRY,DAUNTLESS,GALLANT,PLUCK,VALIANT,VALOR;EASY:FACILE;CALM:APLOMB,IMPASSIVE,NONCHALANT,,PLACID,SERENE,TRANQUIL~IDEALISTIC:QUIXOTIC,UTOPIAN;FEARFUL:COWER,CRAVEN,CRINGE,DAUNT,PETRIFY,PUSILLANIMOUS,TREPIDATION;CORRECT/REPAIR:AMEND,ATONE,EXPIATE,INDEMNIFY,REDRESS,REPARATION,RESTITUTION;EXCESSIVE FLATTERY:FAWN,SYCOPHANT~UNINTENTIONALLY:INADVERTENTLY,UNWITTINGLY;NOT BIASED:DISINTERESTED;WEAKEN:ATTENUATE,ATTRITION,DEGENERATE,ENERVATE,FLAGGING,SAP,WILT;TRIVIAL:EXPENDABLE,INCIDENTAL,MARGINALIZATION,PERIPHERAL";

const kList6 =
    "DISLOYALTY:BETRAY,PERFIDY;CLEAR:ELUCIDATE,LIMPID,LUCID,PELLUCID;PRESENT EVERYWHERE:OMNIPRESENT,UBIQUITOUS;NATIVE:INDIGENOUS~NOT HARMONIOUS:DISCORD,DISCREPANCY,FACTION,INCOMPATIBLE;DIFFICULT TO UNDERSTAND :ABSTRACT,ARCANE,ESOTERIC,OCCULT,PROFOUND,RECONDITE;BAD REPUTATION:IGNOMINY,INFAMY,NOTORIOUS;CONFUSE:ASTOUND,BAFFLE,BEWILDER,CONFOUND,FLABBERGASTED,PERPLEX,STUPEFY~GLOOMY:BLEAK,SOMBER;SUMMARY:CRUX,GIST,SYNOPSIS;EXPERT:CONNOISSEUR,VIRTUOSO;REPETITIOUS:MONOTONOUS,TEDIOUS~EMBARRASS:ABASH,DISCOMFIT,MORTIFY;DELAY:ADJOURN,DEFER,PROCRASTINATE;INCLUDE EVERYTHING:COMPREHENSIVE,ENCOMPASS,PERVASIVE;NOT FLUENT:LABORED;DEPRESSED:ANGUISH,BLEAK,CRESTFALLEN,DEJECTED,DESOLATE,FORLORN,LUGUBRIOUS,MELANCHOLY";

dynamic kGetWordList(int ch) {
  switch (ch) {
    case 1:
      return kList1;
    case 2:
      return kList2;
    case 3:
      return kList3;
    case 4:
      return kList4;
    case 5:
      return kList5;
    case 6:
      return kList6;
    default:
      return '';
  }
}
